### PR TITLE
list params signature is incorrect

### PR DESCRIPTION
**Pull request by syed**
When creating the signature, params which are of type 'list' shoulld be handled correctly.

### CODE REVIEW

**Comment by syed** [comment]
Also added a logger and sync param

**Comment by syed** [comment]
These are my final changes for now. Let me know if you find something

**Comment by swill** [comment]
Its merged.  I will update pypy...

**Comment by swill** [comment]
I have updated Pypy and I have also pushed some new code to add the --async flag to the `CLI` class and made it available in the `cli_example.py` doc string.  Thanks dude...  :)

**Pull request merged**
